#!/bin/bash



echo "Welcome to EXIM services"

read -p "Enter the recipient mail : " usr

file="sys_file_${usr}.txt"

echo "System Report  at $(date) " > "$file"
echo " " 

echo "HELLO !!! " >> "$file"
echo "This is an automated email generated by $(hostname) at the time $(date)" >> "$file"
echo " " 

echo "CPU usage : $(lscpu)" >> "$file" 2>/dev/null
echo " "
echo "Memory usage : $(free -h)" >> "$file" 2>/dev/null
echo " "
echo "Disk usage : $(df -h)" >> "$file" 2>/dev/null
echo " " 

echo "END of the report" >> "$file"


exim -v "$usr" < "$file"


echo "The mail has been sent to $usr"

